theme: jekyll-theme-minimal
title: Tabs Lite
description: THE open source guitar tablature application built for Android.  Thousands of songs available using an existing popular tabs database. Built for speed and simplicity, 100% free with no ads!
logo: img/icon.png